# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  # MR template
  - trigger: ":mr"
    replace: |
             # #1 issue
             
             ## O que foi feito?
             
             - 
             
             ## Preview

  - trigger: ":review"
    replace: |
             **Ambiente**: Arch Linux
             
             **Navegadores**: Firefox
             
             **Cenário**:
            
             - Logado com o usuário admin

             **O que foi testado:**

             - 

             **Resultado**: APROVADO ✅ ou ERRO ENCONTRADO 🛑

             **Comentários**:

             <details><summary>Comentario</summary>

             </details>
